title: your_name.dev
description: Embedded systems & hardware prototyping
url: "https://jpkerkhoff-dev.github.io"
baseurl: ""

author:
  name: jpkerkhoff
  location: Brazil
  status: open to work
  email: jpedev02@gmail.com
  github: jpkerkhoff-dev
  linkedin: jpkerkhoff
  #hackaday: your-hackaday

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

theme: null

plugins:
  - jekyll-feed

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules